### PR TITLE
add .spec-file to package smuview for Fedora

### PR DESCRIPTION
**Pull request by gvegidy**

### CODE REVIEW

**Comment by knarfS** [comment]
I've done some additions to your patch in my branch "rpm":
- The Git hashes, commit date and version string are inserted by CMake
- I removed the stuff directory from the spec file
- The spec file is created into the CMake binary (build) directory

Please check my changes.

What's about the leading/missing percent symbols in the %build section?
Maybe we can get rid of the commit date? Or is that a Fedora/RPM convention?

**Comment by gvegidy** [comment]
Thanks for looking into this.

>     * The Git hashes, commit date and version string are inserted by CMake
>     * The spec file is created into the CMake binary (build) directory

hmm. This depends on the usecase of the person compiling the package:
* does he already have cloned the repo or just downloaded the raw .spec from github?
* does he want to use cmake to just create a matching .spec?

If I just want to build an rpm to be able to install and uninstall it in a clean way, then I'd prefer not needing a full checkout and interacting manually with cmake.

If I regularly develop on smuview, then using a local tree is fine. But then you also want to create the source .tar.gz locally and not download it from github.

> What's about the leading/missing percent symbols in the %build section?

you mean no % before "make manual-html"?
The other ones are macros provided by the rpm infrastructure. The macros take care of the build path, using multiple cores and so on. 
"make manual-html" is just the command, without all this stuff.

> Maybe we can get rid of the commit date? Or is that a Fedora/RPM convention?

The first part of the Release-tag must be increasing for a newer version, otherwise you can't easily upgrade. rpm must know which version is newer. As commit ids are nearly random, the common workaround is to prefix the date in iso format.

Building RPMs for individual git commits isn't perfect. The process isn't as optimized, as it is seldomly used. Most times tagged and numbered releases are packaged and maybe some important patches cherry picked from upstream added.

From a packaging perspective, it would be best if you could introduce "micro releases". If you developed some new feature or fixed some bugs on a weekend, just give it a new version number and tag it. No complicated process, no week-long testing, no release candidates,... Version numbers aren't expensive and don't mean much regarding expectations and so on. I don't see a problem in having a new micro release every week or two. Release early, release often.

If you'd use tagged releases, all the date and git commit id stuff instantly goes away and you just have the version number in the .spec and are done.

But that is of course completely your call to make and not mine.

**Comment by knarfS** [comment]
> If I just want to build an rpm to be able to install and uninstall it in a clean way, then I'd prefer not needing a full checkout and interacting manually with cmake.
> 
> If I regularly develop on smuview, then using a local tree is fine. But then you also want to create the source .tar.gz locally and not download it from github.

Thanks for clarifying.
I wasn't aware that you only need the spec file to create a RPM package, but now it all makes much more sense (e.g. patches in the spec file)!

> From a packaging perspective, it would be best if you could introduce "micro releases". If you developed some new feature or fixed some bugs on a weekend, just give it a new version number and tag it. [...]
> 
> If you'd use tagged releases, all the date and git commit id stuff instantly goes away and you just have the version number in the .spec and are done.

That is my game plan anyways. Also releasing more often, results in more recent AppImages and Windwos installers for users without the knowledge of compiling software.

I hope I will find some time over the next weekend to install Fedora into a VM and play around with spectool and rpmbuild.

**Comment by gvegidy** [comment]
> I wasn't aware that you only need the spec file to create a RPM package, but now it all makes much more sense (e.g. patches in the spec file)!

Yes, it is quite convenient. Github provides the source tarballs, spectool does all the downloading for you.

> > From a packaging perspective, it would be best if you could introduce "micro releases". [...]
> That is my game plan anyways. Also releasing more often, results in more recent AppImages and Windwos installers for users without the knowledge of compiling software.

Nice.

I have prepared a .spec example for a tagged release for you here:
https://github.com/gvegidy/smuview/blob/spec-release/contrib/smuview.spec
(won't build because the 0.0.1 is missing my qwt-qt5 fix)

You could insert the one @SV_VERSION_STRING@ and process it with cmake - this time it is just one string, so I don't think anyone directly downloading it from github would mind replacing that manually. That was just an issue with all the commit ids making it complicated.

**Pull request closed without merging**
